### ISSUE TITLE
Getting Error when trying to run MVN install on windows..

### ISSUE THREAD

**Issue by raghavendranvenkateswaran** [srinandan/wsdl2apigee#8]
INFO: Retrieved WSDL endpoint: http://wsf.cdyne.com/WeatherWS/Weather.asmx
Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Parsed WSDL Successfully.
Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Base Path: /foo
WSDL Path: http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL
Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Build Folder: C:\Users\387823\AppData\Local\Temp\3525789997475750520
SOAP Version: SOAP11
Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Proxy Name: Weather
Proxy Description: Weather
Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Generated Apigee proxy file.
Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Copied standard policies.
Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy writeTargetEndpoint
INFO: Generated Target xml: C:\Users\387823\AppData\Local\Temp\3525789997475750520\apiproxy\targets\default.xml
Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Generated target XML.
Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Generated Apigee Edge API Bundle file: Weather.zip
Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy begin
SEVERE: C:\Users\387823\AppData\Local\Temp\3525789997475750520\apiproxy\proxies\default.xml: The process cannot access the file because it is being u
ed by another process.

Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy prepareTargetFolder
INFO: Target proxy folder setup complete
Jul 14, 2016 11:13:55 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Read operations map
Jul 14, 2016 11:13:56 AM com.apigee.proxywriter.GenerateProxy parseWSDL
INFO: Retrieved WSDL endpoint: http://wsf.cdyne.com/WeatherWS/Weather.asmx
Jul 14, 2016 11:13:56 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Parsed WSDL Successfully.
Jul 14, 2016 11:13:56 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Base Path: /foo
WSDL Path: http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL
Jul 14, 2016 11:13:56 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Build Folder: C:\Users\387823\AppData\Local\Temp\243511184057154342
SOAP Version: SOAP11
Jul 14, 2016 11:13:56 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Proxy Name: Weather
Proxy Description: WhateverWeather
Jul 14, 2016 11:13:56 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Generated Apigee proxy file.
Jul 14, 2016 11:13:56 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Generated SOAP Message Templates.
Jul 14, 2016 11:13:56 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Generated proxies XML.
Jul 14, 2016 11:13:57 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Copied standard policies.
Jul 14, 2016 11:13:57 AM com.apigee.proxywriter.GenerateProxy writeTargetEndpoint
INFO: Generated Target xml: C:\Users\387823\AppData\Local\Temp\243511184057154342\apiproxy\targets\default.xml
Jul 14, 2016 11:13:57 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Generated target XML.
Jul 14, 2016 11:13:57 AM com.apigee.proxywriter.GenerateProxy begin
INFO: Generated Apigee Edge API Bundle file: Weather.zip
Jul 14, 2016 11:13:57 AM com.apigee.proxywriter.GenerateProxy begin
SEVERE: C:\Users\387823\AppData\Local\Temp\243511184057154342\apiproxy\policies\GetCityForecastByZIP-build-soap.xml: The process cannot access the fi
e because it is being used by another process.

Tests run: 7, Failures: 2, Errors: 4, Skipped: 0, Time elapsed: 17.932 sec <<< FAILURE!
testOpsMap1(com.apigee.proxywriter.GenerateProxyTest)  Time elapsed: 1.343 sec  <<< ERROR!
java.lang.NullPointerException
        at com.apigee.proxywriter.GenerateProxyTest.testOpsMap1(GenerateProxyTest.java:183)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testOpsMap2(com.apigee.proxywriter.GenerateProxyTest)  Time elapsed: 0.522 sec  <<< ERROR!
java.lang.NullPointerException
        at com.apigee.proxywriter.GenerateProxyTest.testOpsMap2(GenerateProxyTest.java:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testGenerateRest(com.apigee.proxywriter.GenerateProxyTest)  Time elapsed: 9.668 sec  <<< FAILURE!
java.lang.AssertionError: Missing apiproxy/policies\extract-format.xml
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at com.apigee.proxywriter.GenerateProxyTest.checkForFilesInBundle(GenerateProxyTest.java:24)
        at com.apigee.proxywriter.GenerateProxyTest.testGenerateRest(GenerateProxyTest.java:115)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testCors(com.apigee.proxywriter.GenerateProxyTest)  Time elapsed: 1.67 sec  <<< ERROR!
java.lang.NullPointerException
        at com.apigee.proxywriter.GenerateProxyTest.testCors(GenerateProxyTest.java:151)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testGeneratePassthrough(com.apigee.proxywriter.GenerateProxyTest)  Time elapsed: 1.592 sec  <<< FAILURE!
java.lang.AssertionError: Missing apiproxy/policies\Extract-Operation-Name.xml
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at com.apigee.proxywriter.GenerateProxyTest.checkForFilesInBundle(GenerateProxyTest.java:24)
        at com.apigee.proxywriter.GenerateProxyTest.testGeneratePassthrough(GenerateProxyTest.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

testVHosts(com.apigee.proxywriter.GenerateProxyTest)  Time elapsed: 1.644 sec  <<< ERROR!
java.lang.NullPointerException
        at com.apigee.proxywriter.GenerateProxyTest.testVHosts(GenerateProxyTest.java:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Failed tests:   testGenerateRest(com.apigee.proxywriter.GenerateProxyTest): Missing apiproxy/policies\extract-format.xml
  testGeneratePassthrough(com.apigee.proxywriter.GenerateProxyTest): Missing apiproxy/policies\Extract-Operation-Name.xml

Tests in error:
  testOpsMap1(com.apigee.proxywriter.GenerateProxyTest)
  testOpsMap2(com.apigee.proxywriter.GenerateProxyTest)
  testCors(com.apigee.proxywriter.GenerateProxyTest)
  testVHosts(com.apigee.proxywriter.GenerateProxyTest)

Tests run: 7, Failures: 2, Errors: 4, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.195 s
[INFO] Finished at: 2016-07-14T11:13:57+05:30
[INFO] Final Memory: 9M/75M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project wsdl2apigee: There are test failu
es.
[ERROR]
[ERROR] Please refer to D:\Raghav\Softwares\wsdl2apigee-master\wsdl2apigee-master\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by srinandan** [comment]
Can you please perform a git pull and try again? There was a bug and that has been fixed.

**Comment by raghavendranvenkateswaran** [comment]
Tried again now. It is still giving same error...

**Comment by srinandan** [comment]
I can't reproduce the error. Would you like for me to start the a WebEx/Goto Meeting and see what is happening?

**Comment by raghavendranvenkateswaran** [comment]
Sure , let me know suitable time

**Comment by raghavendranvenkateswaran** [comment]
Issue is fixed now and work on ubuntu and linux
